/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\public\models\characters\character-skeleton.glb -t 
*/

import { EntityShadow } from '@/components/entities/EntityShadow';
import { Enemy } from '@/components/types/GameTypes';
import { useEnemyMovement } from '@/hooks/useEnemyMovement';
import { useAnimations, useGLTF } from '@react-three/drei';
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
} from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type ActionName =
  | 'static'
  | 'idle'
  | 'walk'
  | 'sprint'
  | 'jump'
  | 'fall'
  | 'crouch'
  | 'sit'
  | 'drive'
  | 'die'
  | 'pick-up'
  | 'emote-yes'
  | 'emote-no'
  | 'holding-right'
  | 'holding-left'
  | 'holding-both'
  | 'holding-right-shoot'
  | 'holding-left-shoot'
  | 'holding-both-shoot'
  | 'attack-melee-right'
  | 'attack-melee-left'
  | 'attack-kick-right'
  | 'attack-kick-left'
  | 'interact-right'
  | 'interact-left';
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    ['leg-left']: THREE.Mesh;
    ['leg-right']: THREE.Mesh;
    torso: THREE.Mesh;
    ['arm-left']: THREE.Mesh;
    ['arm-right']: THREE.Mesh;
    head: THREE.Mesh;
  };
  materials: {
    colormap: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

interface SkeletonProps {
  enemy: Enemy;
  enemyId: number;
  yOffset?: number;
}

export const Skeleton = forwardRef(function Orc(
  props: JSX.IntrinsicElements['group'] & SkeletonProps,
  forwardedRef
) {
  const position = useMemo(() => props.position, []);

  const skeleton = useRef<THREE.Group>(null);
  useImperativeHandle(forwardedRef, () => skeleton.current);
  const { nodes, materials, animations } = useGLTF(
    '/models/characters/character-skeleton.glb'
  ) as GLTFResult;

  const { actions } = useAnimations(animations, skeleton);
  const [animation, setAnimation] = useState<ActionName>('idle');

  const MovementSpeed = 0.32;

  useEffect(() => {
    if (!actions) {
      return () => {};
    } else {
      actions[animation]?.reset().fadeIn(0.32).play();
      return () => actions[animation]?.fadeOut(0.32);
    }
  }, [actions, animation]);

  useEnemyMovement(
    skeleton,
    props.position as THREE.Vector3,
    props.yOffset ?? 0,
    props.enemy.movementPoints,
    setAnimation,
    'walk',
    'idle',
    MovementSpeed
  );

  return (
    <group ref={skeleton} {...props} position={position} dispose={null}>
      <EntityShadow />
      <group name="character-skeleton">
        <group name="character-skeleton_1">
          <group name="root">
            <mesh
              name="leg-left"
              geometry={nodes['leg-left'].geometry}
              material={materials.colormap}
              position={[0.074, 0.223, 0]}
              scale={0.858}
            />
            <mesh
              name="leg-right"
              geometry={nodes['leg-right'].geometry}
              material={materials.colormap}
              position={[-0.074, 0.223, 0]}
              scale={0.858}
            />
            <mesh
              name="torso"
              geometry={nodes.torso.geometry}
              material={materials.colormap}
              position={[0, 0.223, 0]}
            >
              <mesh
                name="arm-left"
                geometry={nodes['arm-left'].geometry}
                material={materials.colormap}
                position={[0.15, 0.225, 0.003]}
              />
              <mesh
                name="arm-right"
                geometry={nodes['arm-right'].geometry}
                material={materials.colormap}
                position={[-0.15, 0.225, 0.003]}
              />
              <mesh
                name="head"
                geometry={nodes.head.geometry}
                material={materials.colormap}
                position={[0, 0.26, 0]}
              />
            </mesh>
          </group>
        </group>
      </group>
    </group>
  );
});

useGLTF.preload('/models/characters/character-skeleton.glb');
