/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 .\public\models\items\pendant.glb -t 
*/

import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Pendant: THREE.Mesh;
    Icosphere: THREE.Mesh;
  };
  materials: {
    colormap: THREE.MeshStandardMaterial;
  };
};

//type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Pendant(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/items/pendant.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Pendant.geometry}
        material={materials.colormap}
        position={[0, 0.239, 0]}
      >
        <mesh
          geometry={nodes.Icosphere.geometry}
          material={materials.colormap}
          position={[-0.029, 0, 0]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload('/models/items/pendant.glb');
