/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 .\public\models\traps\BladeTrap.glb -t
*/

import { useStore } from '@/stores/useStore';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { useRef } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';
import { Point2D } from '../../../utils/Point2D';
import useGameObject from '../../entities/useGameObject';
import useGameObjectEvent from '../../entities/useGameObjectEvent';
import { OnTickEvent, PLAYER_DAMAGED_TRAP } from '../../types/EventTypes';
import { Hazard, StatusEffectType } from '../../types/GameTypes';
import useGame from '../../useGame';

type GLTFResult = GLTF & {
  nodes: {
    BladeTrap: THREE.Mesh;
    Blade: THREE.Mesh;
  };
  materials: {
    colormap: THREE.MeshStandardMaterial;
  };
};

type BladeTrapProps = JSX.IntrinsicElements['group'] & {
  data: Hazard;
};

// Relative offsets for each 45° rotation step (clockwise)
const BLADE_STEPS: Array<[Point2D, Point2D]> = [
  [
    { x: 0, y: -1 },
    { x: 0, y: 1 },
  ], // step 0: N + S
  [
    { x: 1, y: 1 },
    { x: -1, y: -1 },
  ], // step 1: NE + SW
  [
    { x: 1, y: 0 },
    { x: -1, y: 0 },
  ], // step 2: E + W
  [
    { x: 1, y: -1 },
    { x: -1, y: 1 },
  ], // step 3: SE + NW
];

export function BladeTrap(props: BladeTrapProps) {
  const { nodes, materials } = useGLTF(
    '/models/traps/BladeTrap.glb'
  ) as GLTFResult;
  const bladeRef = useRef<THREE.Mesh>(null);
  const bladeAngle = useRef(0);
  const isAnimating = useRef(false);
  const step = useRef(1);
  const {} = useGameObject();
  const { publish } = useGame();
  const addLocationsToDangerZones = useStore(
    (s) => s.addLocationsToDangerZones
  );
  const playerInDamageZone = useStore((s) => s.playerInDamageZone);
  const hasStatusEffect = useStore((s) => s.hasStatusEffect);

  useGameObjectEvent<OnTickEvent>('on-tick', () => {
    const origin = props.data.worldPosition;
    const currentBlades = BLADE_STEPS[step.current];
    const nextStep = (step.current + 1) % 4;
    const nextBlades = BLADE_STEPS[nextStep];

    // Show danger zones at next blade positions
    addLocationsToDangerZones([
      { x: origin.x + nextBlades[0].x, y: origin.y + nextBlades[0].y },
      { x: origin.x + nextBlades[1].x, y: origin.y + nextBlades[1].y },
    ]);

    // Advance target angle 45° clockwise
    bladeAngle.current += Math.PI / 4;
    isAnimating.current = true;

    // Damage player if standing on either current blade tip
    const damagePositions: Point2D[] = [
      { x: origin.x + currentBlades[0].x, y: origin.y + currentBlades[0].y },
      { x: origin.x + currentBlades[1].x, y: origin.y + currentBlades[1].y },
    ];
    if (
      !hasStatusEffect(StatusEffectType.FLYING) &&
      playerInDamageZone(damagePositions)
    ) {
      publish(PLAYER_DAMAGED_TRAP, { hazard: props.data });
    }

    step.current = nextStep;
  });

  useFrame(() => {
    if (!isAnimating.current || !bladeRef.current) return;
    const next = THREE.MathUtils.lerp(
      bladeRef.current.rotation.y,
      bladeAngle.current,
      0.15
    );
    bladeRef.current.rotation.y = next;
    if (Math.abs(next - bladeAngle.current) < 0.001) {
      bladeRef.current.rotation.y = bladeAngle.current;
      isAnimating.current = false;
    }
  });

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BladeTrap.geometry} material={materials.colormap}>
        <mesh
          ref={bladeRef}
          geometry={nodes.Blade.geometry}
          material={nodes.Blade.material}
          position={[0, 0.35, 0]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload('/models/traps/BladeTrap.glb');
