/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./public/3Sided-Wall.glb -t 
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0001: THREE.Mesh;
    Mesh_0001_1: THREE.Mesh;
    Mesh_0001_2: THREE.Mesh;
  };
  materials: {
    ['grey-light.001']: THREE.MeshStandardMaterial;
    ['dark.001']: THREE.MeshStandardMaterial;
    ['grey.001']: THREE.MeshStandardMaterial;
  };
};

export function ThreeSidedWall(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3Sided-Wall.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_0001.geometry}
        material={materials['grey-light.001']}
      />
      <mesh
        geometry={nodes.Mesh_0001_1.geometry}
        material={materials['dark.001']}
      />
      <mesh
        geometry={nodes.Mesh_0001_2.geometry}
        material={materials['grey.001']}
      />
    </group>
  );
}

useGLTF.preload('/3Sided-Wall.glb');
