/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 .\public\models\destructables\barrel.glb -t 
*/

import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    barrel_1: THREE.Mesh;
  };
  materials: {
    colormap: THREE.MeshStandardMaterial;
  };
};

export function Barrel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/destructables/barrel.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.barrel_1.geometry} material={materials.colormap} />
    </group>
  );
}

useGLTF.preload('/models/destructables/barrel.glb');
