/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\public\models\items\chalice.glb -t 
*/

import * as THREE from 'three';
import React, { useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    Chalice_Cube023: THREE.Mesh;
  };
  materials: {
    colormap: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const [visible] = useState(true);
  const myRef = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    '/models/items/chalice.glb'
  ) as GLTFResult;

  useFrame(() => {
    if (myRef && myRef.current && myRef.current.rotation) {
      myRef.current.rotation.y += 0.03;
    }
  });

  return (
    <group {...props} dispose={null}>
      {visible && (
        <mesh
          geometry={nodes.Chalice_Cube023.geometry}
          material={materials.colormap}
          position={[0, 0.079, 0]}
          rotation={[Math.PI / 2, -0.609, 0]}
          scale={0.529}
        />
      )}
    </group>
  );
}

useGLTF.preload('/models/items/chalice.glb');
