/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 .\public\models\environment\floor-detail.glb -t 
*/

import { useGLTF, useTexture } from '@react-three/drei';
import { useMemo } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ['floor-detail_1']: THREE.Mesh;
  };
  materials: {
    colormap: THREE.MeshStandardMaterial;
  };
};

interface FloorDetailProps {
  variant?: number;
}

export default function FloorDetail(
  props: JSX.IntrinsicElements['group'] & FloorDetailProps
) {
  const { nodes, materials } = useGLTF(
    '/models/environment/floor-detail.glb'
  ) as GLTFResult;

  const variationTexture = useTexture('/textures/variation-b.png');
  variationTexture.flipY = false; // for glTF models.
  variationTexture.colorSpace = 'srgb';
  variationTexture.name = 'colormap';
  variationTexture.wrapS = THREE.RepeatWrapping;
  variationTexture.wrapT = THREE.RepeatWrapping;

  const floorMaterial = useMemo(() => {
    if (props.variant && props.variant == 1) {
      const material = new THREE.MeshStandardMaterial().copy(
        materials.colormap
      );
      material.map = variationTexture;
      return material;
    } else {
      return materials.colormap;
    }
  }, [materials.colormap, props.variant, variationTexture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes['floor-detail_1'].geometry}
        material={floorMaterial}
      />
    </group>
  );
}

useGLTF.preload('/models/environment/floor-detail.glb');
