/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./public/models/environment/floor.glb -t
*/

import { useGLTF, useTexture } from '@react-three/drei';
import { useEffect, useMemo } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: { floor_1: THREE.Mesh };
  materials: { colormap: THREE.MeshStandardMaterial };
};

interface FloorProps {
  variant?: number;
  tint?: number;
}

export default function Floor({ tint, ...props }: JSX.IntrinsicElements['group'] & FloorProps) {
  const { nodes, materials } = useGLTF('/models/environment/floor.glb') as GLTFResult;
  const variationTexture = useTexture('/textures/variation-b.png');

  useEffect(() => {
    variationTexture.flipY = false;
    variationTexture.needsUpdate = true;
  }, [variationTexture]);

  const material = useMemo(() => {
    const mat = materials.colormap.clone();
    if (props.variant === 1) mat.map = variationTexture;
    return mat;
  }, [materials.colormap, props.variant, variationTexture]);

  useEffect(() => {
    material.color.setScalar(tint ?? 1.0);
  }, [material, tint]);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.floor_1.geometry} material={material} />
    </group>
  );
}

useGLTF.preload('/models/environment/floor.glb');
