/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 .\public\models\environment\floor-detail.glb -t
*/

import { useGLTF, useTexture } from '@react-three/drei';
import { useEffect, useMemo } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: { ['floor-detail_1']: THREE.Mesh };
  materials: { colormap: THREE.MeshStandardMaterial };
};

interface FloorDetailProps {
  variant?: number;
  tint?: number;
}

export default function FloorDetail({ tint, ...props }: JSX.IntrinsicElements['group'] & FloorDetailProps) {
  const { nodes, materials } = useGLTF('/models/environment/floor-detail.glb') as GLTFResult;

  const variationTexture = useTexture('/textures/variation-b.png');

  useEffect(() => {
    variationTexture.flipY = false;
    variationTexture.colorSpace = 'srgb';
    variationTexture.name = 'colormap';
    variationTexture.wrapS = THREE.RepeatWrapping;
    variationTexture.wrapT = THREE.RepeatWrapping;
    variationTexture.needsUpdate = true;
  }, [variationTexture]);

  const material = useMemo(() => {
    const mat = materials.colormap.clone();
    if (props.variant === 1) mat.map = variationTexture;
    return mat;
  }, [materials.colormap, props.variant, variationTexture]);

  useEffect(() => {
    material.color.setScalar(tint ?? 1.0);
  }, [material, tint]);

  useEffect(() => {
    return () => {
      material.dispose();
    };
  }, [material]);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['floor-detail_1'].geometry} material={material} />
    </group>
  );
}

useGLTF.preload('/models/environment/floor-detail.glb');
