/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 .\public\models\environment\LiquidWall-All.glb -t 
*/

import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';
import { LiquidType } from '../types/GameTypes';
import { useLiquidSpriteSheet } from './useLiquidSpriteSheet';

type GLTFResult = GLTF & {
  nodes: {
    ['Liquid-All']: THREE.Mesh;
    ['LWall-Half']: THREE.Mesh;
    ['LWall-Lshape']: THREE.Mesh;
    ['LWall-Narrow']: THREE.Mesh;
    ['LWall-ThreeSided']: THREE.Mesh;
  };
  materials: {
    colormap: THREE.MeshStandardMaterial;
  };
};

export enum LiquidWallType {
  TYPE_ALL,
  TYPE_HALF,
  TYPE_LSHAPE,
  TYPE_NARROW,
  TYPE_THREESIDED,
  TYPE_NONE,
}

export type LiquidProps = JSX.IntrinsicElements['group'] & {
  liquidType: LiquidType;
  wallType: LiquidWallType;
};

export function LiquidWallAll(props: LiquidProps) {
  const { spriteSheet } = useLiquidSpriteSheet(props.liquidType);

  const { nodes, materials } = useGLTF(
    '/models/environment/LiquidWall-All.glb'
  ) as GLTFResult;

  return (
    <group {...props} dispose={null}>
      {props.wallType === LiquidWallType.TYPE_HALF && (
        <mesh
          geometry={nodes['LWall-Half'].geometry}
          material={materials.colormap}
        />
      )}
      {props.wallType === LiquidWallType.TYPE_LSHAPE && (
        <mesh
          geometry={nodes['LWall-Lshape'].geometry}
          material={materials.colormap}
        />
      )}
      {props.wallType === LiquidWallType.TYPE_NARROW && (
        <mesh
          geometry={nodes['LWall-Narrow'].geometry}
          material={materials.colormap}
        />
      )}
      {props.wallType === LiquidWallType.TYPE_THREESIDED && (
        <mesh
          geometry={nodes['LWall-ThreeSided'].geometry}
          material={materials.colormap}
        />
      )}
      {props.wallType === LiquidWallType.TYPE_ALL && (
        <mesh
          geometry={nodes['Liquid-All'].geometry}
          material={materials.colormap}
        />
      )}
      <mesh
        rotation={[THREE.MathUtils.degToRad(270), 0, 0]}
        position={[0, -0.25, 0]}
      >
        <planeGeometry attach="geometry" args={[1, 1]} />
        <meshBasicMaterial
          attach="material"
          side={THREE.FrontSide}
          map={spriteSheet}
          transparent
        />
      </mesh>
    </group>
  );
}

useGLTF.preload('/models/environment/LiquidWall-All.glb');
