/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 .\public\models\environment\LiquidWall-All.glb -t

NOTE: Tinting liquid tiles (explored fog-of-war) may look visually odd. The
wall geometry and the animated sprite sheet plane are both tinted together,
but the sprite's colour animation can make the effect look muddy rather than
simply darker. Adjust EXPLORED_TINT in ShowEnvironment.tsx or remove tint
from liquid cases there if the explored effect looks wrong.
*/

import { useGLTF } from '@react-three/drei';
import { useEffect, useMemo, useRef } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';
import { LiquidType } from '../types/GameTypes';
import { useLiquidSpriteSheet } from './useLiquidSpriteSheet';

type GLTFResult = GLTF & {
  nodes: {
    ['Liquid-All']: THREE.Mesh;
    ['LWall-Half']: THREE.Mesh;
    ['LWall-Lshape']: THREE.Mesh;
    ['LWall-Narrow']: THREE.Mesh;
    ['LWall-ThreeSided']: THREE.Mesh;
  };
  materials: {
    colormap: THREE.MeshStandardMaterial;
  };
};

export enum LiquidWallType {
  TYPE_ALL,
  TYPE_HALF,
  TYPE_LSHAPE,
  TYPE_NARROW,
  TYPE_THREESIDED,
  TYPE_NONE,
}

export type LiquidProps = JSX.IntrinsicElements['group'] & {
  liquidType: LiquidType;
  wallType: LiquidWallType;
  tint?: number;
};

export function LiquidWallAll({ tint, liquidType, wallType, ...props }: LiquidProps) {
  const { spriteSheet } = useLiquidSpriteSheet(liquidType);
  const { nodes, materials } = useGLTF('/models/environment/LiquidWall-All.glb') as GLTFResult;

  const wallMaterial = useMemo(() => materials.colormap.clone(), [materials.colormap]);
  const spriteMaterialRef = useRef<THREE.MeshBasicMaterial>(null);

  useEffect(() => {
    const scalar = tint ?? 1.0;
    wallMaterial.color.setScalar(scalar);
    if (spriteMaterialRef.current) {
      spriteMaterialRef.current.color.setScalar(scalar);
    }
  }, [wallMaterial, tint]);

  return (
    <group {...props} dispose={null}>
      {wallType === LiquidWallType.TYPE_HALF && (
        <mesh geometry={nodes['LWall-Half'].geometry} material={wallMaterial} />
      )}
      {wallType === LiquidWallType.TYPE_LSHAPE && (
        <mesh geometry={nodes['LWall-Lshape'].geometry} material={wallMaterial} />
      )}
      {wallType === LiquidWallType.TYPE_NARROW && (
        <mesh geometry={nodes['LWall-Narrow'].geometry} material={wallMaterial} />
      )}
      {wallType === LiquidWallType.TYPE_THREESIDED && (
        <mesh geometry={nodes['LWall-ThreeSided'].geometry} material={wallMaterial} />
      )}
      {wallType === LiquidWallType.TYPE_ALL && (
        <mesh geometry={nodes['Liquid-All'].geometry} material={wallMaterial} />
      )}
      <mesh
        rotation={[THREE.MathUtils.degToRad(270), 0, 0]}
        position={[0, -0.25, 0]}
      >
        <planeGeometry attach="geometry" args={[1, 1]} />
        <meshBasicMaterial
          ref={spriteMaterialRef}
          attach="material"
          side={THREE.FrontSide}
          map={spriteSheet}
          transparent
        />
      </mesh>
    </group>
  );
}

useGLTF.preload('/models/environment/LiquidWall-All.glb');
