/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\public\models\environment\LShape-Wall.glb -t
*/

import { useGLTF } from '@react-three/drei';
import { useEffect, useMemo } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: { ['wall-lshape']: THREE.Mesh };
  materials: { colormap: THREE.MeshStandardMaterial };
};

interface LShapeWallProps {
  tint?: number;
}

export function LShapeWall({ tint, ...props }: JSX.IntrinsicElements['group'] & LShapeWallProps) {
  const { nodes, materials } = useGLTF('/models/environment/LShape-Wall.glb') as GLTFResult;

  const material = useMemo(() => materials.colormap.clone(), [materials.colormap]);

  useEffect(() => {
    material.color.setScalar(tint ?? 1.0);
  }, [material, tint]);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['wall-lshape'].geometry} material={material} />
    </group>
  );
}

useGLTF.preload('/models/environment/LShape-Wall.glb');
