/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 .\public\models\environment\stairs.glb -t
*/

import * as THREE from 'three';
import React, { useEffect, useMemo } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: { stairs_1: THREE.Mesh };
  materials: { colormap: THREE.MeshStandardMaterial };
};

interface StairsProps {
  tint?: number;
}

export default function Stairs({ tint, ...props }: JSX.IntrinsicElements['group'] & StairsProps) {
  const { nodes, materials } = useGLTF('/models/environment/stairs.glb') as GLTFResult;

  const material = useMemo(() => materials.colormap.clone(), [materials.colormap]);

  useEffect(() => {
    material.color.setScalar(tint ?? 1.0);
  }, [material, tint]);

  useEffect(() => {
    return () => { material.dispose(); };
  }, [material]);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.stairs_1.geometry} material={material} />
    </group>
  );
}

useGLTF.preload('/models/environment/stairs.glb');
