/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./public/3Sided-Wall.glb -t
*/

import { useGLTF } from '@react-three/drei';
import { useEffect, useMemo } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: { 'wall-threesided': THREE.Mesh };
  materials: { colormap: THREE.MeshStandardMaterial };
};

interface ThreeSidedWallProps {
  tint?: number;
}

export function ThreeSidedWall({ tint, ...props }: JSX.IntrinsicElements['group'] & ThreeSidedWallProps) {
  const { nodes, materials } = useGLTF('/models/environment/3Sided-Wall.glb') as GLTFResult;

  const material = useMemo(() => materials.colormap.clone(), [materials.colormap]);

  useEffect(() => {
    material.color.setScalar(tint ?? 1.0);
  }, [material, tint]);

  useEffect(() => {
    return () => { material.dispose(); };
  }, [material]);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['wall-threesided'].geometry} material={material} />
    </group>
  );
}

useGLTF.preload('/models/environment/3Sided-Wall.glb');
