/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./public/wall-narrow.glb -t 
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh;
    mesh_0_1: THREE.Mesh;
    mesh_0_2: THREE.Mesh;
  };
  materials: {
    ['grey-light']: THREE.MeshStandardMaterial;
    dark: THREE.MeshStandardMaterial;
    grey: THREE.MeshStandardMaterial;
  };
};

export function WallNarrow(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/wall-narrow.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.mesh_0.geometry}
        material={materials['grey-light']}
      />
      <mesh geometry={nodes.mesh_0_1.geometry} material={materials.dark} />
      <mesh geometry={nodes.mesh_0_2.geometry} material={materials.grey} />
    </group>
  );
}

useGLTF.preload('/wall-narrow.glb');
