/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 .\public\models\environment\wall-narrow.glb -t
*/

import * as THREE from 'three';
import React, { useEffect, useMemo } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: { ['wall-narrow_1']: THREE.Mesh };
  materials: { colormap: THREE.MeshStandardMaterial };
};

interface WallNarrowProps {
  tint?: number;
}

export default function WallNarrow({ tint, ...props }: JSX.IntrinsicElements['group'] & WallNarrowProps) {
  const { nodes, materials } = useGLTF('/models/environment/wall-narrow.glb') as GLTFResult;

  const material = useMemo(() => materials.colormap.clone(), [materials.colormap]);

  useEffect(() => {
    material.color.setScalar(tint ?? 1.0);
  }, [material, tint]);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['wall-narrow_1'].geometry} material={material} />
    </group>
  );
}

useGLTF.preload('/models/environment/wall-narrow.glb');
