/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./public/models/environment/floor.glb -t

NOTE: Tinting liquid tiles (explored fog-of-war) may look visually odd since
water materials have coloured/emissive properties that don't darken naturally.
Adjust EXPLORED_TINT in ShowEnvironment.tsx or remove tint from liquid cases
if the explored effect looks wrong.
*/

import { useGLTF } from '@react-three/drei';
import { useEffect, useMemo } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: { floor: THREE.Mesh };
  materials: { colormap: THREE.MeshStandardMaterial };
};

interface WaterProps {
  tint?: number;
}

export default function Water({ tint, ...props }: JSX.IntrinsicElements['group'] & WaterProps) {
  const { nodes, materials } = useGLTF('/models/environment/water.glb') as GLTFResult;

  const material = useMemo(() => materials.colormap.clone(), [materials.colormap]);

  useEffect(() => {
    material.color.setScalar(tint ?? 1.0);
  }, [material, tint]);

  useEffect(() => {
    return () => { material.dispose(); };
  }, [material]);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.floor.geometry} material={material} />
    </group>
  );
}

useGLTF.preload('/models/environment/water.glb');
